# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/design_1_fwheun_0_0.xci
# IP: The module: 'design_1_fwheun_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i0/fwheun_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i0 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i1/fwheun_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i1 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i2/fwheun_c_addsub_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i2 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i3/fwheun_c_addsub_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i3 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i4/fwheun_c_addsub_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i4 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i5/fwheun_c_addsub_v12_0_i5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i5 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i5} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i6/fwheun_c_addsub_v12_0_i6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i6 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i6} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i7/fwheun_c_addsub_v12_0_i7.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i7 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i7} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i0/fwheun_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i0 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i1/fwheun_mult_gen_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i1 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i2/fwheun_mult_gen_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i2 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i2} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i3/fwheun_mult_gen_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i3 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i3} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i4/fwheun_mult_gen_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i4 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i4} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i5/fwheun_mult_gen_v12_0_i5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i5 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i5} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i6/fwheun_mult_gen_v12_0_i6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i6 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i6} -quiet] -quiet

# XDC: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/constrs/fwheun.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fwheun_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/design_1_fwheun_0_0.xci
# IP: The module: 'design_1_fwheun_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i0/fwheun_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i0 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i1/fwheun_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i1 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i2/fwheun_c_addsub_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i2 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i3/fwheun_c_addsub_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i3 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i4/fwheun_c_addsub_v12_0_i4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i4 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i5/fwheun_c_addsub_v12_0_i5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i5 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i5} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i6/fwheun_c_addsub_v12_0_i6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i6 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i6} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_c_addsub_v12_0_i7/fwheun_c_addsub_v12_0_i7.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_c_addsub_v12_0_i7 || ORIG_REF_NAME==fwheun_c_addsub_v12_0_i7} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i0/fwheun_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i0 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i1/fwheun_mult_gen_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i1 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i2/fwheun_mult_gen_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i2 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i2} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i3/fwheun_mult_gen_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i3 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i3} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i4/fwheun_mult_gen_v12_0_i4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i4 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i4} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i5/fwheun_mult_gen_v12_0_i5.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i5 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i5} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/fwheun_mult_gen_v12_0_i6/fwheun_mult_gen_v12_0_i6.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fwheun_mult_gen_v12_0_i6 || ORIG_REF_NAME==fwheun_mult_gen_v12_0_i6} -quiet] -quiet

# XDC: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/fw-heun/fourwing/fourwing.srcs/sources_1/bd/design_1/ip/design_1_fwheun_0_0/constrs/fwheun.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_fwheun_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
