# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/design_1_lorenz_hardware_0_1.xci
# IP: The module: 'design_1_lorenz_hardware_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_c_addsub_v12_0_i0/lorenz_hardware_c_addsub_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_c_addsub_v12_0_i0 || ORIG_REF_NAME==lorenz_hardware_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_c_addsub_v12_0_i1/lorenz_hardware_c_addsub_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_c_addsub_v12_0_i1 || ORIG_REF_NAME==lorenz_hardware_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_c_addsub_v12_0_i2/lorenz_hardware_c_addsub_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_c_addsub_v12_0_i2 || ORIG_REF_NAME==lorenz_hardware_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_c_addsub_v12_0_i3/lorenz_hardware_c_addsub_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_c_addsub_v12_0_i3 || ORIG_REF_NAME==lorenz_hardware_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_c_addsub_v12_0_i4/lorenz_hardware_c_addsub_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_c_addsub_v12_0_i4 || ORIG_REF_NAME==lorenz_hardware_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_mult_gen_v12_0_i0/lorenz_hardware_mult_gen_v12_0_i0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_mult_gen_v12_0_i0 || ORIG_REF_NAME==lorenz_hardware_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_mult_gen_v12_0_i1/lorenz_hardware_mult_gen_v12_0_i1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_mult_gen_v12_0_i1 || ORIG_REF_NAME==lorenz_hardware_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_mult_gen_v12_0_i2/lorenz_hardware_mult_gen_v12_0_i2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_mult_gen_v12_0_i2 || ORIG_REF_NAME==lorenz_hardware_mult_gen_v12_0_i2} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_mult_gen_v12_0_i3/lorenz_hardware_mult_gen_v12_0_i3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_mult_gen_v12_0_i3 || ORIG_REF_NAME==lorenz_hardware_mult_gen_v12_0_i3} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_mult_gen_v12_0_i4/lorenz_hardware_mult_gen_v12_0_i4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_mult_gen_v12_0_i4 || ORIG_REF_NAME==lorenz_hardware_mult_gen_v12_0_i4} -quiet] -quiet

# XDC: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/constrs/lorenz_hardware.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_lorenz_hardware_0_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/design_1_lorenz_hardware_0_1.xci
# IP: The module: 'design_1_lorenz_hardware_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_c_addsub_v12_0_i0/lorenz_hardware_c_addsub_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_c_addsub_v12_0_i0 || ORIG_REF_NAME==lorenz_hardware_c_addsub_v12_0_i0} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_c_addsub_v12_0_i1/lorenz_hardware_c_addsub_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_c_addsub_v12_0_i1 || ORIG_REF_NAME==lorenz_hardware_c_addsub_v12_0_i1} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_c_addsub_v12_0_i2/lorenz_hardware_c_addsub_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_c_addsub_v12_0_i2 || ORIG_REF_NAME==lorenz_hardware_c_addsub_v12_0_i2} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_c_addsub_v12_0_i3/lorenz_hardware_c_addsub_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_c_addsub_v12_0_i3 || ORIG_REF_NAME==lorenz_hardware_c_addsub_v12_0_i3} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_c_addsub_v12_0_i4/lorenz_hardware_c_addsub_v12_0_i4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_c_addsub_v12_0_i4 || ORIG_REF_NAME==lorenz_hardware_c_addsub_v12_0_i4} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_mult_gen_v12_0_i0/lorenz_hardware_mult_gen_v12_0_i0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_mult_gen_v12_0_i0 || ORIG_REF_NAME==lorenz_hardware_mult_gen_v12_0_i0} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_mult_gen_v12_0_i1/lorenz_hardware_mult_gen_v12_0_i1.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_mult_gen_v12_0_i1 || ORIG_REF_NAME==lorenz_hardware_mult_gen_v12_0_i1} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_mult_gen_v12_0_i2/lorenz_hardware_mult_gen_v12_0_i2.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_mult_gen_v12_0_i2 || ORIG_REF_NAME==lorenz_hardware_mult_gen_v12_0_i2} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_mult_gen_v12_0_i3/lorenz_hardware_mult_gen_v12_0_i3.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_mult_gen_v12_0_i3 || ORIG_REF_NAME==lorenz_hardware_mult_gen_v12_0_i3} -quiet] -quiet

# IP: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/lorenz_hardware_mult_gen_v12_0_i4/lorenz_hardware_mult_gen_v12_0_i4.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==lorenz_hardware_mult_gen_v12_0_i4 || ORIG_REF_NAME==lorenz_hardware_mult_gen_v12_0_i4} -quiet] -quiet

# XDC: c:/Users/cakef/Documents/GitHub/pynq-math-visualisations/lorenz/lorenz/lorenz.srcs/sources_1/bd/design_1/ip/design_1_lorenz_hardware_0_1/constrs/lorenz_hardware.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_lorenz_hardware_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
